g1 = {   'board': {   'food': [{'x': 3, 'y': 9}, {'x': 5, 'y': 5}],
             'height': 11,
             'snakes': [   {   'body': [   {'x': 10, 'y': 0},
                                           {'x': 10, 'y': 1},
                                           {'x': 10, 'y': 2},
                                           {'x': 10, 'y': 3},
                                           {'x': 10, 'y': 4}],
                               'health': 74,
                               'id': 'gs_rYmjCvMpV4SCV8bQ9vJDM4vY',
                               'name': 'jstolp / Domme Gewone Pofadder'}],
             'width': 11},
'game': {'id': '8dc0561f-a4f6-4568-9ef5-0bfd7c006c41'},
'turn': 96,
'you': {   'body': [   {'x': 3, 'y': 8},
                       {'x': 2, 'y': 8},
                       {'x': 2, 'y': 9},
                       {'x': 2, 'y': 10},
                       {'x': 3, 'y': 10},
                       {'x': 4, 'y': 10},
                       {'x': 4, 'y': 9},
                       {'x': 4, 'y': 8},
                       {'x': 4, 'y': 7},
                       {'x': 4, 'y': 6},
                       {'x': 4, 'y': 5},
                       {'x': 4, 'y': 4},
                       {'x': 4, 'y': 3},
                       {'x': 4, 'y': 2},
                       {'x': 3, 'y': 2},
                       {'x': 2, 'y': 2},
                       {'x': 2, 'y': 3}],
           'health': 86,
           'id': 'gs_GHR47YTvwVQ6t3M8dhKCT7xM',
           'name': 'otonnesen / test snake 2'}}

g2 = {   'board': {   'food': [   {'x': 3, 'y': 9},
                             {'x': 10, 'y': 10},
                             {'x': 7, 'y': 0},
                             {'x': 6, 'y': 10}],
                 'height': 11,
                 'snakes': [   {   'body': [   {'x': 1, 'y': 1},
                                               {'x': 1, 'y': 1},
                                               {'x': 1, 'y': 1}],
                                   'health': 100,
                                   'id': 'gs_hRqYp4cPxhTtBcFGQb3DP3Yc',
                                   'name': 'otonnesen / test snake 2'},
                               {   'body': [   {'x': 9, 'y': 9},
                                               {'x': 9, 'y': 9},
                                               {'x': 9, 'y': 9}],
                                   'health': 100,
                                   'id': 'gs_PqR4x6Ht6c8fT7RKMYX3hdgF',
                                   'name': 'foleya / DotaAutoSnake'},
                               {   'body': [   {'x': 1, 'y': 9},
                                               {'x': 1, 'y': 9},
                                               {'x': 1, 'y': 9}],
                                   'health': 100,
                                   'id': 'gs_hQ8QDxpKdb9fHmDrfPhmQRcJ',
                                   'name': 'jonknoll / Siamese Fighting Snake'},
                               {   'body': [   {'x': 9, 'y': 1},
                                               {'x': 9, 'y': 1},
                                               {'x': 9, 'y': 1}],
                                   'health': 100,
                                   'id': 'gs_33bXRhJ33YfqJvBbBcw4QBfS',
                                   'name': 'PhoenixProgrammer / '
                                           'PhoenixProgramming'}],
                 'width': 11},
    'game': {'id': '68e542fb-b25c-49c3-bbd2-36bc9e8322ba'},
    'turn': 0,
    'you': {   'body': [{'x': 1, 'y': 1}, {'x': 1, 'y': 1}, {'x': 1, 'y': 1}],
               'health': 100,
               'id': 'gs_hRqYp4cPxhTtBcFGQb3DP3Yc',
               'name': 'otonnesen / test snake 2'}}

def main():
    pass

if __name__ == '__main__':
    main()
